---
- name: Install AWS CLI and download S3 file
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    s3_bucket: "sanjay-3879"
    s3_object: "sanjay.txt"
    download_path: "/home/ec2-user/sanjay.txt"

  tasks:

    - name: Install unzip and Python3
      package:
        name:
          - unzip
          - python3
        state: present

    - name: Download AWS CLI v2 zip
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: /tmp/awscliv2.zip
        mode: '0644'

    - name: Unzip AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Install AWS CLI
      shell: "/tmp/aws/install"
      args:
        creates: /usr/local/bin/aws

    - name: Clean AWS CLI installer files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/awscliv2.zip
        - /tmp/aws

    - name: Ensure destination directory exists
      file:
        path: "/home/ec2-user"
        state: directory
        mode: '0755'

    - name: Download S3 file
      amazon.aws.aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ s3_object }}"
        dest: "{{ download_path }}"
        mode: get

    - name: Set ownership and permissions of downloaded S3 file
      file:
        path: "{{ download_path }}"
        owner: ec2-user
        group: ec2-user
        mode: '0644'


