---
- name: Configure RDS Database
  hosts: localhost
  connection: local
  vars:
    rds_endpoint: "{{ rds_endpoint }}"   # Passed from Terraform user_data
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    db_name: Mini_Project

  tasks:
    - name: Create Database
      shell: |
        mysql -h {{ rds_endpoint }} -u {{ db_user }} -p'{{ db_password }}' \
        -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
      ignore_errors: yes

    - name: Create Table
      shell: |
        mysql -h {{ rds_endpoint }} -u {{ db_user }} -p'{{ db_password }}' -D {{ db_name }} \
        -e "CREATE TABLE IF NOT EXISTS testdata (
              Name VARCHAR(50),
              Contact VARCHAR(15),
              Address VARCHAR(100)
            );"
      ignore_errors: yes

    - name: Insert Sample Data
      shell: |
        mysql -h {{ rds_endpoint }} -u {{ db_user }} -p'{{ db_password }}' -D {{ db_name }} \
        -e "INSERT INTO testdata (Name, Contact, Address)
            VALUES
            ('sanjay', '1234567890', 'Dublin'),
            ('alice', '9876543210', 'London'),
            ('bob', '5555555555', 'New York');"
      ignore_errors: yes

    - name: Verify Table Data
      shell: |
        mysql -h {{ rds_endpoint }} -u {{ db_user }} -p'{{ db_password }}' -D {{ db_name }} \
        -e "SELECT * FROM testdata;"
      register: query_result

    - name: Display Query Output
      debug:
        var: query_result.stdout_lines

