---
- name: Configure RDS MySQL Database
  hosts: local
  connection: local
  vars:
    db_name: Mini_Project
    table_name: testdata
    sample_data:
      - Name: sanjay
        Contact: "1234567890"
        Address: Dublin
      - Name: ajay
        Contact: "9876543210"
        Address: London
      - Name: harsha
        Contact: "5555555555"
        Address: Paris
  tasks:

    - name: Install MySQL client if not present
      package:
        name: mysql
        state: present

    - name: Ensure Python MySQL module is installed
      pip:
        name: PyMySQL
        state: present

    - name: Create Database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ rds_endpoint }}"

    - name: Create Table
      community.mysql.mysql_table:
        name: "{{ table_name }}"
        db: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ rds_endpoint }}"
        columns:
          - name: Name
            type: VARCHAR(50)
          - name: Contact
            type: VARCHAR(20)
          - name: Address
            type: VARCHAR(50)

    - name: Insert Sample Data
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ rds_endpoint }}"
        db: "{{ db_name }}"
        query: >
          INSERT INTO {{ table_name }} (Name, Contact, Address)
          VALUES
          {% for row in sample_data %}
            ('{{ row.Name }}', '{{ row.Contact }}', '{{ row.Address }}'){% if not loop.last %},{% endif %}
          {% endfor %};

    - name: Verify inserted data
      community.mysql.mysql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ rds_endpoint }}"
        db: "{{ db_name }}"
        query: "SELECT * FROM {{ table_name }};"
      register: query_result

    - name: Show data from table
      debug:
        var: query_result.query_result

